denoise:
  country: Taiwan
  strategy: with_cot
  # strategy: without_cot
  model: gpt-4-1106-preview
  temperature: 0.
  timeout: 120
  verbose: False
  experiment_name: auto-EPU
  run_name: with_cot_fewshot6
  query_file_path: data/test_10.jsonl


fine_tune:
  input_dir: data/raw
  output_dir: data/processed/fine_tune
  n: 10
  strategy: no_reason
  # strategy: with_reason
  n_epochs: 30
  train_file: example00.jsonl
  val_file:
  # val_file: example02.jsonl
