denoise:
  country: Taiwan
  strategy: with_cot
  # strategy: without_cot

  # parameters for OpenAILLM
  model: gpt-3.5-turbo-1106
  temperature: 0.
  timeout: 120
  verbose: False

  # set experiment and run for MLflow tracking
  experiment_name: auto-EPU
  run_name: with_cot_fewshot6

  # file for LLM to label documents
  query_file_path: test.jsonl

# TODO:
fine_tune:
  input_dir: data/raw
  output_dir: data/processed/fine_tune
  n: 10
  strategy: no_reason
  # strategy: with_reason
  n_epochs: 30
  train_file: example00.jsonl
  val_file:
  # val_file: example02.jsonl
