hydra:
    output_subdir: null
    run:
      dir: .


defaults:
    - model: openai
    - _self_


keyword:
  task: definition
  # task: simple

  # this parameter should be set if it's "simple" task
  cate: economic
  # cate: policy
  # cate: uncertanty

  role: newspaper editor
  # role: economist
  # role: Minister of Economic Affairs
  # role: Central Bank Governor

  n_items: 20

  # below are some language(country) specfic parameter
  nationality: a Taiwanese
  # nationality: an American
  # nationality: a Chinese
  # nationality: a South Korean
  # nationality: a Japanese
